/**
 * abrgNormalizeCases.ts
 *
 * @description abr-geocoder 3.0.51 の normalize パッケージのテストの入力と期待値（THIRD_PARTY_NOTICES）
 */

import type { AddressType } from '../../src/domain/abrgNormalize.ts';

/** 入力と期待値。source は移植元のテストのファイル・関数・行 */
export interface StringCase {
  source: string;
  name: string;
  input: string;
  expected: string;
  changed?: boolean;
}

/** 住所の整形の入力と期待値 */
export interface FormatCase {
  source: string;
  name: string;
  input: string;
  expected: string;
  addressType: AddressType;
}

/** 住所の型の判定の入力と期待値 */
export interface TypeCase {
  source: string;
  name: string;
  input: string;
  expected: AddressType;
}

export const ADDRESS_NUMBERS_TO_HYPHEN_CASES: StringCase[] = [
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L13',
    name: 'banchi/N番地N号_基本',
    input: '1番地2号',
    expected: '1-2',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L19',
    name: 'banchi/N番地N棟_建物番号',
    input: '1番地1棟301号',
    expected: '1 1棟301号',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L25',
    name: 'banchi/N番地のN_ひらがな',
    input: '1番地の2',
    expected: '1-2',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L31',
    name: 'banchi/N番地ノN_カタカナ',
    input: '26番地ノ1',
    expected: '26-1',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L37',
    name: 'banchi/N番地-N号_ハイフン付き',
    input: '101番地-2808号',
    expected: '101-2808',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L43',
    name: 'banchi/N番地N号_連続数字',
    input: '101番地3602号',
    expected: '101-3602',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L49',
    name: 'banchi/N番地M-P号_ハイフン枝番',
    input: '玉川4丁目4番地1-999号',
    expected: '玉川4丁目4-1-999',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L55',
    name: 'banchi/N番地-M_ハイフン枝番号なし',
    input: '玉川4丁目4番地-11',
    expected: '玉川4丁目4-11',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L61',
    name: 'banchi/N番地N_後続数字',
    input: '1番地2',
    expected: '1-2',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L67',
    name: 'banchi/N番地_末尾',
    input: '9999番地',
    expected: '9999',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L73',
    name: 'banchi/N番地+建物名',
    input: '129番地ツインビル',
    expected: '129 ツインビル',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L79',
    name: 'banchi/N番地M+建物名',
    input: '11番地2さいたま新都心LAタワー30F',
    expected: '11-2 さいたま新都心LAタワー30F',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L85',
    name: 'banchi/N番地M+ビル名階',
    input: '4番地3ウェルクビル5階',
    expected: '4-3 ウェルクビル5階',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L92',
    name: 'ban/N番N号_基本',
    input: '1番3号',
    expected: '1-3',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L98',
    name: 'ban/N番N-M号_ハイフン1つ',
    input: '1番2-3号',
    expected: '1-2-3',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L104',
    name: 'ban/N番N-M-O号_ハイフン2つ',
    input: '1番2-3-4号',
    expected: '1-2-3-4',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L110',
    name: 'ban/N番N-M-O-P-Q号_ハイフン多数',
    input: '1番2-3-4-5-6号',
    expected: '1-2-3-4-5-6',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L116',
    name: 'ban/N番N-英数字号_部屋番号',
    input: '22番5-A1002号',
    expected: '22-5 -A1002',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L122',
    name: 'ban/N番N_後続数字',
    input: '1番3',
    expected: '1-3',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L128',
    name: 'ban/N番_末尾',
    input: '1310番',
    expected: '1310',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L134',
    name: 'ban/N番_住所末尾',
    input: '神奈川県川崎市幸区大宮町1310番',
    expected: '神奈川県川崎市幸区大宮町1310',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L140',
    name: 'ban/N番のN_ひらがな',
    input: '510番の1',
    expected: '510-1',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L146',
    name: 'ban/N番のN_住所付き',
    input: '愛知県小牧市大字河内屋新田字下岩倉杁510番の1',
    expected: '愛知県小牧市大字河内屋新田字下岩倉杁510-1',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L153',
    name: 'negative/既にハイフン化済み',
    input: '1-2-3',
    expected: '1-2-3',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L159',
    name: 'negative/空文字列',
    input: '',
    expected: '',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L166',
    name: 'real/風祭154番1',
    input: '神奈川県小田原市風祭154番1',
    expected: '神奈川県小田原市風祭154-1',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L172',
    name: 'real/大宮町1310番',
    input: '神奈川県川崎市幸区大宮町1310番',
    expected: '神奈川県川崎市幸区大宮町1310',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L178',
    name: 'real/四之宮7番4',
    input: '神奈川県平塚市四之宮一丁目7番4',
    expected: '神奈川県平塚市四之宮一丁目7-4',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L184',
    name: 'real/蒼前東9番28',
    input: '青森県三戸郡階上町蒼前東二丁目9番28',
    expected: '青森県三戸郡階上町蒼前東二丁目9-28',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L190',
    name: 'real/滝ノ沢100番9',
    input: '青森県南津軽郡大鰐町大字島田字滝ノ沢100番9',
    expected: '青森県南津軽郡大鰐町大字島田字滝ノ沢100-9',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L196',
    name: 'real/紺屋町4番8',
    input: '静岡市葵区紺屋町4番8',
    expected: '静岡市葵区紺屋町4-8',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L203',
    name: 'ban/N番M棟_建物番号',
    input: '千葉県船橋市行田三丁目1番12棟206号',
    expected: '千葉県船橋市行田三丁目1 12棟206号',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L209',
    name: 'ban/N番M棟_半角数字',
    input: '千葉県船橋市習志野台六丁目8番4棟304号',
    expected: '千葉県船橋市習志野台六丁目8 4棟304号',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L215',
    name: 'special/N番街_商業施設',
    input: '東京都港区台場一丁目5番街1号棟601号室',
    expected: '東京都港区台場一丁目5番街 1号棟601号室',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L221',
    name: 'ban/N番+建物名_カタカナ',
    input: '神戸市中央区京町80番クリエイト神戸9階',
    expected: '神戸市中央区京町80 クリエイト神戸9階',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L227',
    name: 'ban/N番+建物名_同番号',
    input: '神戸市中央区江戸町104番江戸町104ビル4階',
    expected: '神戸市中央区江戸町104 江戸町104ビル4階',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L233',
    name: 'ban/N番NのN+建物名',
    input: '東京都千代田区西神田二丁目6番7の2共和15番館ビル2階',
    expected: '東京都千代田区西神田二丁目6-7-2 共和15番館ビル2階',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L239',
    name: 'banchi/N番地N号棟_建物番号',
    input: '埼玉県三郷市早稲田六丁目1番地2号棟201号',
    expected: '埼玉県三郷市早稲田六丁目1 2号棟201号',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L245',
    name: 'ban/N番N-N号室_部屋番号',
    input: '東京都千代田区三崎町三丁目2番6-1104号室レジディア水道橋',
    expected: '東京都千代田区三崎町三丁目2-6 -1104号室レジディア水道橋',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L251',
    name: 'banchi/N番地N号_琴平町',
    input: '香川県仲多度郡琴平町榎井106番地5号',
    expected: '香川県仲多度郡琴平町榎井106-5',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L257',
    name: 'ban/NのN号+建物名',
    input: '東京都千代田区一番町20の6号一番町マンション101号',
    expected: '東京都千代田区一番町20-6 一番町マンション101号',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L263',
    name: 'ban/N番M号+部屋番号',
    input: '10番27号516',
    expected: '10-27 516',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L269',
    name: 'ban/N番M号+部屋番号_建物名',
    input: '5番23号1丁目マンション301',
    expected: '5-23 1丁目マンション301',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L275',
    name: 'special/N-N-N号_末尾号',
    input: '東京都江東区豊洲五丁目1-13-4107号',
    expected: '東京都江東区豊洲五丁目1-13-4107',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L282',
    name: 'special/N番先_末尾',
    input: '東京都中央区銀座四丁目1番先',
    expected: '東京都中央区銀座四丁目1番先',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L288',
    name: 'special/N番先+建物名',
    input: '東京都中央区銀座四丁目1番先西銀座デパートB2F',
    expected: '東京都中央区銀座四丁目1番先 西銀座デパートB2F',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L294',
    name: 'special/N番先+読点+建物名',
    input: '東京都中央区銀座四丁目1番先、北数寄屋ビル地下1階',
    expected: '東京都中央区銀座四丁目1番先 、北数寄屋ビル地下1階',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L300',
    name: 'special/N番先+直接建物名',
    input: '東京都中央区銀座四丁目1番先北数寄屋ビル地下1階',
    expected: '東京都中央区銀座四丁目1番先 北数寄屋ビル地下1階',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L306',
    name: 'special/N番屋敷_基本',
    input: '神戸市海岸通三丁目2番屋敷',
    expected: '神戸市海岸通三丁目2番屋敷',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L312',
    name: 'special/N番屋敷_大きい番号',
    input: '神戸市元町通四丁目137番屋敷',
    expected: '神戸市元町通四丁目137番屋敷',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L318',
    name: 'special/N番戸',
    input: '北海道札幌市中央区南一条西五丁目15番戸',
    expected: '北海道札幌市中央区南一条西五丁目15番戸',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L324',
    name: 'special/N号地N_複合',
    input: '東京都千代田区神田佐久間河岸71号地1',
    expected: '東京都千代田区神田佐久間河岸71号地1',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L330',
    name: 'special/N号地_単独',
    input: '東京都千代田区神田佐久間河岸78号地',
    expected: '東京都千代田区神田佐久間河岸78号地',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L337',
    name: 'bancho/一番町N+建物名1',
    input: '東京都千代田区一番町5アトラスビル5階',
    expected: '東京都千代田区一番町5 アトラスビル5階',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L343',
    name: 'bancho/一番町N+建物名2',
    input: '東京都千代田区一番町6一番町スクエア5階',
    expected: '東京都千代田区一番町6 一番町スクエア5階',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L349',
    name: 'bancho/一番町N+建物名3',
    input: '東京都千代田区一番町6相模屋本社ビル7F',
    expected: '東京都千代田区一番町6 相模屋本社ビル7F',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L355',
    name: 'bancho/九番町N+建物名',
    input: '東京都千代田区九番町3ビジネスセンター',
    expected: '東京都千代田区九番町3 ビジネスセンター',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L361',
    name: 'bancho/三番町N+建物名',
    input: '東京都千代田区三番町12大妻女子大学',
    expected: '東京都千代田区三番町12 大妻女子大学',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L367',
    name: 'bancho/二番町N番-N',
    input: '東京都千代田区二番町1番-2',
    expected: '東京都千代田区二番町1-2',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L373',
    name: 'bancho/二番町N番N-N',
    input: '東京都千代田区二番町1番2-732',
    expected: '東京都千代田区二番町1-2-732',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L379',
    name: 'bancho/備前町N番N-N',
    input: '茨城県水戸市備前町7番32-610',
    expected: '茨城県水戸市備前町7-32-610',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L385',
    name: 'special/N-N-N室_部屋番号',
    input: '東京都千代田区永田町二丁目17-10-202室',
    expected: '東京都千代田区永田町二丁目17-10 -202室',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L391',
    name: 'bancho/三番町N番+建物名',
    input: '東京都千代田区三番町五丁目11番パークハウス三番町1301号',
    expected: '東京都千代田区三番町五丁目11 パークハウス三番町1301号',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L397',
    name: 'bancho/四番町N番-N号',
    input: '東京都千代田区四番町六丁目11番-1004号',
    expected: '東京都千代田区四番町六丁目11-1004',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L403',
    name: 'bancho/四番町N番N+建物名',
    input: '東京都千代田区四番町9番10パークコート四番町1003号',
    expected: '東京都千代田区四番町9-10 パークコート四番町1003号',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L409',
    name: 'ban/N番N-英数字_部屋番号1',
    input: '東京都中央区日本橋箱崎町44番5-B1201',
    expected: '東京都中央区日本橋箱崎町44-5 -B1201',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L415',
    name: 'ban/N番N-英数字_部屋番号2',
    input: '東京都中央区日本橋箱崎町44番5-B501',
    expected: '東京都中央区日本橋箱崎町44-5 -B501',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L422',
    name: 'negative/N街区M号_基本',
    input: '宮崎県都城市平江町13街区5号',
    expected: '宮崎県都城市平江町13街区5号',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L428',
    name: 'negative/N街区M号_別例',
    input: '宮崎県都城市姫城町32街区3号',
    expected: '宮崎県都城市姫城町32街区3号',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L435',
    name: 'special/N-N-N-NF_フロア表記',
    input: '東京都千代田区平河町2-2-5-1F',
    expected: '東京都千代田区平河町2-2-5 -1F',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L441',
    name: 'special/N番地先+建物名',
    input: '東京都中央区銀座五丁目4番地先数寄屋橋シヨツピングセンター内223号',
    expected:
      '東京都中央区銀座五丁目4番地先 数寄屋橋シヨツピングセンター内223号',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L447',
    name: 'special/N番耕地N番地N',
    input: '愛媛県八幡浜市大字郷1番耕地12番地1',
    expected: '愛媛県八幡浜市大字郷1番耕地12-1',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L453',
    name: 'special/N-N-N階',
    input: '東京都千代田区平河町二丁目5-3-5階',
    expected: '東京都千代田区平河町二丁目5-3 -5階',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L460',
    name: 'negative/N番町N街区',
    input: '桔梗が丘6番町3街区',
    expected: '桔梗が丘6番町3街区',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L467',
    name: 'negative/地名に番_番ケ谷',
    input: '津山市1宮1番ケ谷1031',
    expected: '津山市1宮1番ケ谷1031',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L474',
    name: 'negative/番町N丁目_基本',
    input: '一番町1丁目',
    expected: '一番町1丁目',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L480',
    name: 'negative/番町N丁目_住所付き',
    input: '刈谷市一番町2丁目',
    expected: '刈谷市一番町2丁目',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L487',
    name: 'negative/無番地_村',
    input: '新潟県中蒲原郡新飯田村無番地',
    expected: '新潟県中蒲原郡新飯田村無番地',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L493',
    name: 'negative/無番地_町',
    input: '神奈川県横須賀市田浦港町無番地',
    expected: '神奈川県横須賀市田浦港町無番地',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L499',
    name: 'negative/無番地_大字',
    input: '愛知県海部郡飛島村大字政成新田無番地',
    expected: '愛知県海部郡飛島村大字政成新田無番地',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L506',
    name: 'negative/N街区_末尾',
    input: '愛知県知立市知立駅周辺10街区',
    expected: '愛知県知立市知立駅周辺10街区',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L512',
    name: 'negative/N-N街区_ハイフン付き',
    input: '愛知県知立市知立駅周17-1街区',
    expected: '愛知県知立市知立駅周17-1街区',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L519',
    name: 'negative/条_北1条西1丁目',
    input: '北海道札幌市中央区北1条西1丁目',
    expected: '北海道札幌市中央区北1条西1丁目',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L525',
    name: 'negative/条_北10条東5丁目',
    input: '北海道札幌市東区北10条東5丁目',
    expected: '北海道札幌市東区北10条東5丁目',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L531',
    name: 'negative/条_南3条西4丁目',
    input: '北海道札幌市中央区南3条西4丁目',
    expected: '北海道札幌市中央区南3条西4丁目',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L538',
    name: 'issue87/N番NのN号_基本',
    input: '16番1の50号',
    expected: '16-1-50',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L544',
    name: 'issue87/N番NのN_号なし',
    input: '2番10の1',
    expected: '2-10-1',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L550',
    name: 'issue87/N番地のN号_基本',
    input: '1番地の11号',
    expected: '1-11',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L556',
    name: 'issue87/N番地のN号_別例',
    input: '5番地の3号',
    expected: '5-3',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L562',
    name: 'issue87/N番NノN号_カタカナ',
    input: '10番5ノ2号',
    expected: '10-5-2',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddressNumbersToHyphen L568',
    name: 'issue87/N番地ノN号_カタカナ',
    input: '3番地ノ7号',
    expected: '3-7',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestKanjiBlockGoPattern L831',
    name: '',
    input: '渡辺3号',
    expected: '渡辺3号',
  },
  {
    source: 'address_hyphen_test.go TestSenGoPattern L853',
    name: 'sen-go pattern (N線N号) - keep as is',
    input: '西神楽1線24号',
    expected: '西神楽1線24号',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestSenGoPattern L859',
    name: 'sen-go pattern with full address',
    input: '北海道旭川市西神楽1線24号',
    expected: '北海道旭川市西神楽1線24号',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestSenGoPattern L865',
    name: 'sen-go pattern (東鷹栖1線11号)',
    input: '北海道旭川市東鷹栖1線11号',
    expected: '北海道旭川市東鷹栖1線11号',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestSenGoPattern L872',
    name: 'sen-direction-go pattern (N線西N号) - keep as is',
    input: '10線西5号',
    expected: '10線西5号',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestSenGoPattern L878',
    name: 'sen-direction-go pattern with full address',
    input: '北海道上川郡鷹栖町10線西5号',
    expected: '北海道上川郡鷹栖町10線西5号',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestSenGoPattern L884',
    name: 'sen-direction-go pattern (N線東N号)',
    input: '北海道上川郡鷹栖町10線東3号',
    expected: '北海道上川郡鷹栖町10線東3号',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestSenGoPattern L890',
    name: 'sen-direction-go pattern (N線南N号)',
    input: '北海道上川郡鷹栖町10線南2号',
    expected: '北海道上川郡鷹栖町10線南2号',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestSenGoPattern L896',
    name: 'sen-direction-go pattern (N線北N号)',
    input: '北海道上川郡鷹栖町10線北1号',
    expected: '北海道上川郡鷹栖町10線北1号',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestSenGoPattern L903',
    name: 'sen only pattern',
    input: '北海道上川郡鷹栖町7線',
    expected: '北海道上川郡鷹栖町7線',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestSenGoPattern L910',
    name: 'sen-direction only pattern',
    input: '北海道上川郡鷹栖町10線西',
    expected: '北海道上川郡鷹栖町10線西',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestHokkaidoSpecialPatterns L941',
    name: 'chusen-go pattern - 中線1号 (should NOT convert)',
    input: '北海道士別市温根別町中線1号',
    expected: '北海道士別市温根別町中線1号',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestHokkaidoSpecialPatterns L947',
    name: 'chusen-go pattern - 中線10号 (should NOT convert)',
    input: '北海道士別市温根別町中線10号',
    expected: '北海道士別市温根別町中線10号',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestHokkaidoSpecialPatterns L954',
    name: 'nishikagura-minami-go - 西神楽南13号 (should NOT convert)',
    input: '北海道旭川市西神楽南13号',
    expected: '北海道旭川市西神楽南13号',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestHokkaidoSpecialPatterns L961',
    name: 'akebono pattern - アケボノ1丁目 (should NOT convert ノ1 to -1)',
    input: 'アケボノ1丁目',
    expected: 'アケボノ1丁目',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestHokkaidoSpecialPatterns L967',
    name: 'akebono pattern - 音別町アケボノ1丁目 (should NOT convert)',
    input: '北海道釧路市音別町アケボノ1丁目',
    expected: '北海道釧路市音別町アケボノ1丁目',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestHokkaidoSpecialPatterns L974',
    name: 'furano-no pattern - 南大沼ノ1 (should NOT convert)',
    input: '北海道富良野市南大沼ノ1',
    expected: '北海道富良野市南大沼ノ1',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestHokkaidoSpecialPatterns L980',
    name: 'furano-no pattern - 麓郷市街地ノ4 (should NOT convert)',
    input: '北海道富良野市麓郷市街地ノ4',
    expected: '北海道富良野市麓郷市街地ノ4',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestHokkaidoSpecialPatterns L987',
    name: 'kisen pattern - 岩内町第1基線 (should NOT add space before 基線)',
    input: '北海道帯広市岩内町第1基線',
    expected: '北海道帯広市岩内町第1基線',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestHokkaidoSpecialPatterns L993',
    name: 'kisen pattern - 幌呂原野第2基線 (should NOT add space before 基線)',
    input: '北海道阿寒郡鶴居村幌呂原野第2基線',
    expected: '北海道阿寒郡鶴居村幌呂原野第2基線',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestHokkaidoSpecialPatterns L1000',
    name: 'legitimate no pattern - 6番7の2 (should convert)',
    input: '東京都千代田区6番7の2',
    expected: '東京都千代田区6-7-2',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestBankawaPattern L1028',
    name: '青山奥2番川 - should NOT separate',
    input: '青山奥2番川',
    expected: '青山奥2番川',
  },
  {
    source: 'address_hyphen_test.go TestBankawaPattern L1033',
    name: '青山奥3番川 - should NOT separate',
    input: '青山奥3番川',
    expected: '青山奥3番川',
  },
  {
    source: 'address_hyphen_test.go TestBankawaPattern L1038',
    name: '青山奥4番川 - should NOT separate',
    input: '青山奥4番川',
    expected: '青山奥4番川',
  },
  {
    source: 'address_hyphen_test.go TestBankawaPattern L1043',
    name: 'regular N番 pattern - should convert',
    input: '1丁目2番',
    expected: '1丁目2',
  },
  {
    source: 'address_hyphen_test.go TestBantsuPattern L1169',
    name: '南1番通 - should NOT separate N番通',
    input: '南1番通',
    expected: '南1番通',
  },
  {
    source: 'address_hyphen_test.go TestNoMachiPattern L1303',
    name: '礎町通1ノ町 - should preserve ノ町',
    input: '礎町通1ノ町',
    expected: '礎町通1ノ町',
  },
  {
    source: 'address_hyphen_test.go TestNoMachiPattern L1308',
    name: '礎町通2ノ町 - should preserve ノ町',
    input: '礎町通2ノ町',
    expected: '礎町通2ノ町',
  },
  {
    source: 'address_hyphen_test.go TestNoMachiPattern L1313',
    name: 'regular Nの pattern should still convert',
    input: '町1の2共',
    expected: '町1-2 共',
  },
  {
    source: 'address_hyphen_test.go TestNoMachiPattern L1318',
    name: 'Nの pattern at end should still convert',
    input: '町1の2',
    expected: '町1-2',
  },
];

export const ADD_SPACE_AFTER_FIRST_ARABIC_NUMBER_CASES: StringCase[] = [
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterFirstArabicNumber L614',
    name: 'simple hyphenated pattern',
    input: '1-2-3アトラスビル',
    expected: '1-2-3 アトラスビル',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterFirstArabicNumber L620',
    name: 'already has space',
    input: '1-2-3 ビル',
    expected: '1-2-3 ビル',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterFirstArabicNumber L626',
    name: 'no hyphenated pattern',
    input: '東京都千代田区',
    expected: '東京都千代田区',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterFirstArabicNumber L632',
    name: 'hyphenated pattern with suffix',
    input: '1-2-3ビル',
    expected: '1-2-3 ビル',
    changed: true,
  },
];

export const ADD_SPACE_AFTER_NUMBER_BEFORE_JAPANESE_CASES: StringCase[] = [
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L660',
    name: 'number before katakana building name',
    input: '一番町5アトラス',
    expected: '一番町5 アトラス',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L666',
    name: 'number before kanji building name',
    input: '九番町3東京ビル',
    expected: '九番町3 東京ビル',
    changed: true,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L672',
    name: 'number before 丁目 (should not add space)',
    input: '1丁目',
    expected: '1丁目',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L678',
    name: 'already has space',
    input: '5 アトラス',
    expected: '5 アトラス',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L684',
    name: 'Hokkaido line address - 南9線 (should not add space)',
    input: '姉別原野南9線',
    expected: '姉別原野南9線',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L690',
    name: 'Hokkaido line address - 北1線西 (should not add space)',
    input: '温根別町北1線西',
    expected: '温根別町北1線西',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L696',
    name: 'Hokkaido line address - 新野7線 (should not add space)',
    input: '新野7線',
    expected: '新野7線',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L702',
    name: 'Iwate chiwari address - 第35地割 (should not add space)',
    input: '大更第35地割',
    expected: '大更第35地割',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L708',
    name: 'Iwate chiwari address - 第1地割 (should not add space)',
    input: '平笠第1地割',
    expected: '平笠第1地割',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L714',
    name: 'Fukushima chiwari address - 下地割甲 (should not add space)',
    input: '磐見下地割甲',
    expected: '磐見下地割甲',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L720',
    name: 'Iwate chiwari with koaza - 第8地割800平 (should not add space)',
    input: '鴬宿第8地割800平',
    expected: '鴬宿第8地割800平',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L726',
    name: 'town name with 区 - 北刈谷2区100B (should not add space)',
    input: '刈谷市北刈谷2区100B',
    expected: '刈谷市北刈谷2区100B',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L732',
    name: 'town name with 区 - 北刈谷2区 only (should not add space)',
    input: '北刈谷2区',
    expected: '北刈谷2区',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L740',
    name: '漢字N漢字M丁目 pattern - 東1北2丁目 (should not add space between 1 and 北)',
    input: '中標津町東1北2丁目',
    expected: '中標津町東1北2丁目',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L746',
    name: '漢字N漢字M丁目 pattern - 東6南6丁目 (should not add space between 6 and 南)',
    input: '中標津町東6南6丁目',
    expected: '中標津町東6南6丁目',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L752',
    name: '漢字N漢字M丁目 pattern - 西2北3丁目 (should not add space between 2 and 北)',
    input: '中標津町西2北3丁目',
    expected: '中標津町西2北3丁目',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L760',
    name: 'tree-counting koaza - 3本通線 (should not add space between 3 and 本通)',
    input: '標茶町虹別市街3本通線',
    expected: '標茶町虹別市街3本通線',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L766',
    name: 'tree-counting koaza - 姉大1本松 (should not add space between 1 and 本松)',
    input: '千代田町姉大1本松',
    expected: '千代田町姉大1本松',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L772',
    name: 'tree-counting koaza - 姉2本松 (should not add space between 2 and 本松)',
    input: '千代田町姉2本松',
    expected: '千代田町姉2本松',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L780',
    name: 'field measurement koaza - 8の坪 (should not add space between 8 and の坪)',
    input: '千代田町渡瀬8の坪',
    expected: '千代田町渡瀬8の坪',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L786',
    name: 'field measurement koaza - 8ノ坪 (should not add space between 8 and ノ坪)',
    input: '千代田町渡瀬8ノ坪',
    expected: '千代田町渡瀬8ノ坪',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L794',
    name: 'multi-village communal land - 2ケ村入会地 (should not add space between 2 and ケ村)',
    input: '南砺市井波外2ケ村入会地',
    expected: '南砺市井波外2ケ村入会地',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestAddSpaceAfterNumberBeforeJapanese L800',
    name: 'multi-village communal land - 4ケ村入会地 (should not add space between 4 and ケ村)',
    input: '南砺市井波外4ケ村入会地',
    expected: '南砺市井波外4ケ村入会地',
    changed: false,
  },
  {
    source: 'address_hyphen_test.go TestBunkuPattern L1067',
    name: '11分区 - should NOT insert space before 分区',
    input: '宮戸11分区',
    expected: '宮戸11分区',
  },
  {
    source: 'address_hyphen_test.go TestBunkuPattern L1072',
    name: '1分区 - should NOT insert space before 分区',
    input: '宮戸1分区',
    expected: '宮戸1分区',
  },
  {
    source: 'address_hyphen_test.go TestBunkuPattern L1077',
    name: '5分区 - should NOT insert space before 分区',
    input: '宮戸5分区',
    expected: '宮戸5分区',
  },
  {
    source: 'address_hyphen_test.go TestKihokuKinanPattern L1101',
    name: '第1基北1線 - should NOT insert space before 基北',
    input: '幌呂原野第1基北1線',
    expected: '幌呂原野第1基北1線',
  },
  {
    source: 'address_hyphen_test.go TestKihokuKinanPattern L1106',
    name: '第2基南2線 - should NOT insert space before 基南',
    input: '幌呂原野第2基南2線',
    expected: '幌呂原野第2基南2線',
  },
  {
    source: 'address_hyphen_test.go TestKihokuKinanPattern L1111',
    name: '第1基北1線東 - should NOT insert space before 基北',
    input: '幌呂原野第1基北1線東',
    expected: '幌呂原野第1基北1線東',
  },
  {
    source: 'address_hyphen_test.go TestNotoriPattern L1135',
    name: '太田1の通り - should NOT insert space before の通',
    input: '太田1の通り',
    expected: '太田1の通り',
  },
  {
    source: 'address_hyphen_test.go TestNotoriPattern L1140',
    name: '霧多布村3の通 - should NOT insert space before の通',
    input: '霧多布村3の通',
    expected: '霧多布村3の通',
  },
  {
    source: 'address_hyphen_test.go TestNotoriPattern L1145',
    name: '横15の通 - should NOT insert space before の通',
    input: '横15の通',
    expected: '横15の通',
  },
  {
    source: 'address_hyphen_test.go TestChonaikaiPattern L1193',
    name: '国見14町内会 - should NOT insert space before 町内会',
    input: '国見14町内会',
    expected: '国見14町内会',
  },
  {
    source: 'address_hyphen_test.go TestRinpanPattern L1216',
    name: '国有林71林班 - should NOT insert space before 林班',
    input: '国有林71林班',
    expected: '国有林71林班',
  },
  {
    source: 'address_hyphen_test.go TestRinpanPattern L1221',
    name: '国有林42林班イ小班 - should NOT insert space before 林班',
    input: '国有林42林班イ小班',
    expected: '国有林42林班イ小班',
  },
  {
    source: 'address_hyphen_test.go TestAzaPattern L1245',
    name: '飯山町1字 - should NOT insert space before 字',
    input: '飯山町1字',
    expected: '飯山町1字',
  },
  {
    source: 'address_hyphen_test.go TestAzaPattern L1250',
    name: '鹿島路町10字 - should NOT insert space before 字',
    input: '鹿島路町10字',
    expected: '鹿島路町10字',
  },
  {
    source: 'address_hyphen_test.go TestChoPattern L1274',
    name: '庭代台4丁 - should NOT insert space before 丁',
    input: '庭代台4丁',
    expected: '庭代台4丁',
  },
  {
    source: 'address_hyphen_test.go TestChoPattern L1279',
    name: '茶山台1丁 - should NOT insert space before 丁',
    input: '茶山台1丁',
    expected: '茶山台1丁',
  },
  {
    source: 'address_hyphen_test.go TestNoMachiPatternAddSpace L1342',
    name: '礎町通1ノ町 - should NOT insert space before ノ町',
    input: '礎町通1ノ町',
    expected: '礎町通1ノ町',
  },
  {
    source: 'address_hyphen_test.go TestNoMachiPatternAddSpace L1347',
    name: '礎町通2ノ町 - should NOT insert space before ノ町',
    input: '礎町通2ノ町',
    expected: '礎町通2ノ町',
  },
  {
    source: 'address_hyphen_test.go TestNoMachiPatternAddSpace L1352',
    name: '新潟市中央区礎町通1ノ町 - should NOT insert space before ノ町',
    input: '新潟市中央区礎町通1ノ町',
    expected: '新潟市中央区礎町通1ノ町',
  },
];

export const NORMALIZE_ADDRESS_TEXT_CASES: FormatCase[] = [
  {
    source: 'normalize_test.go TestNormalizeAddressText L17',
    name: 'block comment removal',
    input: '東京都千代田区/* comment */紀尾井町1番3号',
    expected: '東京都千代田区紀尾井町1-3',
    addressType: 'rsdtdsp',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L23',
    name: 'line comment removal',
    input: '東京都千代田区紀尾井町1番3号 // comment',
    expected: '東京都千代田区紀尾井町1-3',
    addressType: 'rsdtdsp',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L31',
    name: 'full-width to half-width conversion',
    input: '東京都千代田区紀尾井町１番３号',
    expected: '東京都千代田区紀尾井町1-3',
    addressType: 'rsdtdsp',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L37',
    name: 'full-width dash normalization',
    input: '東京都千代田区紀尾井町１－２－３',
    expected: '東京都千代田区紀尾井町1-2-3',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L43',
    name: 'katakana prolonged sound mark between numbers',
    input: '東京都千代田区紀尾井町1ー2ー3',
    expected: '東京都千代田区紀尾井町1-2-3',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L49',
    name: 'half-width katakana conversion',
    input: '東京都千代田区紀尾井町1番3号東京ｶﾞｰﾃﾞﾝﾃﾗｽ紀尾井町',
    expected: '東京都千代田区紀尾井町1-3 東京ガーデンテラス紀尾井町',
    addressType: 'rsdtdsp',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L57',
    name: 'multiple spaces normalization',
    input: '東京都\u3000\u3000千代田区\u3000\u3000紀尾井町\u3000\u30001番3号',
    expected: '東京都 千代田区 紀尾井町 1-3',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L63',
    name: 'tab normalization',
    input: '東京都\t千代田区\t紀尾井町\t1番3号',
    expected: '東京都 千代田区 紀尾井町 1-3',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L71',
    name: 'residential pattern (番号)',
    input: '東京都千代田区1番3号',
    expected: '東京都千代田区1-3',
    addressType: 'rsdtdsp',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L77',
    name: 'residential pattern with alphanumeric suffix',
    input: '東京都文京区春日二丁目２２番５－Ａ１００２号',
    expected: '東京都文京区春日二丁目22-5 -A1002',
    addressType: 'rsdtdsp',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L83',
    name: 'residential pattern with hyphen (番-号)',
    input: '東京都千代田区1番2-3号',
    expected: '東京都千代田区1-2-3',
    addressType: 'rsdtdsp',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L89',
    name: 'ban pattern without go',
    input: '東京都千代田区1番3',
    expected: '東京都千代田区1-3',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L95',
    name: 'ban pattern at end of string',
    input: '熊本県菊池郡西合志町御代志字井手向１００１番１１',
    expected: '熊本県菊池郡西合志町御代志字井手向1001-11',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L101',
    name: 'parcel pattern (番地)',
    input: '東京都世田谷区1番地',
    expected: '東京都世田谷区1',
    addressType: 'parcel',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L107',
    name: 'parcel pattern (番地の)',
    input: '東京都世田谷区1番地の2',
    expected: '東京都世田谷区1-2',
    addressType: 'parcel',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L113',
    name: 'parcel pattern (番地N)',
    input: '東京都世田谷区1番地2',
    expected: '東京都世田谷区1-2',
    addressType: 'parcel',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L119',
    name: 'undetermined pattern (arabic dash)',
    input: '東京都千代田区1-2-3',
    expected: '東京都千代田区1-2-3',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L125',
    name: 'undetermined pattern with building - add space',
    input: '東京都千代田区紀尾井町1-2-3東京ガーデンテラス',
    expected: '東京都千代田区紀尾井町1-2-3 東京ガーデンテラス',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L131',
    name: 'undetermined pattern (incorrect banchi-go)',
    input: '東京都千代田区1番地2号',
    expected: '東京都千代田区1-2',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L137',
    name: 'unknown pattern (prefecture only)',
    input: '東京都',
    expected: '東京都',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L145',
    name: 'full processing with all transformations',
    input:
      '東京都/* comment */\u3000\u3000千代田区\u3000\u3000紀尾井町１番３号\u3000\u3000東京ガーデンテラス',
    expected: '東京都 千代田区 紀尾井町1-3 東京ガーデンテラス',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L151',
    name: 'address with building name',
    input: '東京都千代田区紀尾井町1番3号東京ガーデンテラス',
    expected: '東京都千代田区紀尾井町1-3 東京ガーデンテラス',
    addressType: 'rsdtdsp',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L157',
    name: 'trailing spaces after conversion',
    input: '東京都新宿区1番地',
    expected: '東京都新宿区1',
    addressType: 'parcel',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L165',
    name: 'empty string',
    input: '',
    expected: '',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L171',
    name: 'only spaces',
    input: '   \u3000\u3000\u3000   ',
    expected: '',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L177',
    name: 'only comment',
    input: '/* comment */',
    expected: '',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L185',
    name: 'real case - saitama yoshikawa',
    input: '埼玉県吉川市旭９番１',
    expected: '埼玉県吉川市旭9-1',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L191',
    name: 'real case - saitama ageo',
    input: '埼玉県上尾市西宮下二丁目１５５番３',
    expected: '埼玉県上尾市西宮下二丁目155-3',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L197',
    name: 'real case - N番 only',
    input: '埼玉県川崎市幸区大宮町１３１０番',
    expected: '埼玉県川崎市幸区大宮町1310',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L203',
    name: 'real case - 2393番2',
    input: '群馬県利根郡新治村大字入須川２３９３番２',
    expected: '群馬県利根郡新治村大字入須川2393-2',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L209',
    name: 'real case - 1番7',
    input: '広島県大竹市明治新開１番７',
    expected: '広島県大竹市明治新開1-7',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L215',
    name: 'real case - 3番 only',
    input: '宮崎市矢の先町３番',
    expected: '宮崎市矢の先町3',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L221',
    name: 'real case - 555番1',
    input: '宮城県名取市上余田字千刈田５５５番１',
    expected: '宮城県名取市上余田字千刈田555-1',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L227',
    name: 'with carriage return',
    input: '宮城県名取市上余田字千刈田５５５番１\r',
    expected: '宮城県名取市上余田字千刈田555-1',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L233',
    name: 'with newline',
    input: '宮崎市矢の先町３番\n',
    expected: '宮崎市矢の先町3',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L239',
    name: 'hyphenated address with building name - イーストコート',
    input: '神戸市東灘区向洋町中1-14イーストコート2番街',
    expected: '神戸市東灘区向洋町中1-14 イーストコート2番街',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L245',
    name: 'address with parentheses',
    input: '東京都港区(六本木)',
    expected: '東京都港区 (六本木)',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L251',
    name: 'address with comma',
    input: '東京都港区,六本木1-2-3',
    expected: '東京都港区 ,六本木1-2-3',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L257',
    name: 'address with Japanese comma',
    input: '東京都港区、六本木1-2-3',
    expected: '東京都港区 、六本木1-2-3',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L263',
    name: 'address with mixed punctuation',
    input: '神戸市東灘区向洋町中1-14(イーストコート2番街)',
    expected: '神戸市東灘区向洋町中1-14 (イーストコート2番街)',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L269',
    name: 'ban with building and go',
    input: '横浜市金沢区釜利谷南一丁目３番Ｄ−４１７号',
    expected: '横浜市金沢区釜利谷南一丁目3 D-417号',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L275',
    name: 'ban with japanese text and go',
    input: '横浜市青葉区あざみ野三丁目１番あざみ野団地４棟１０４号',
    expected: '横浜市青葉区あざみ野三丁目1 あざみ野団地4棟104号',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L281',
    name: 'ban with building name',
    input: '横浜市中区海岸通二丁目８番第二吉本ビル４階',
    expected: '横浜市中区海岸通二丁目8 第二吉本ビル4階',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L287',
    name: 'chome ban pattern',
    input: '横浜市中区桜木町二丁目２番港陽ビル７階',
    expected: '横浜市中区桜木町二丁目2 港陽ビル7階',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L293',
    name: 'real case - with fullwidth hyphen',
    input: '埼玉県吉川市旭９－１',
    expected: '埼玉県吉川市旭9-1',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L299',
    name: 'real case - with various dashes',
    input: '埼玉県上尾市西宮下二丁目１５５－３－４',
    expected: '埼玉県上尾市西宮下二丁目155-3-4',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L305',
    name: 'ban tou pattern with full-width',
    input: '千葉県船橋市行田三丁目１番１２棟２０６号',
    expected: '千葉県船橋市行田三丁目1 12棟206号',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L311',
    name: 'ban tou pattern',
    input: '千葉県船橋市習志野台六丁目8番4棟304号',
    expected: '千葉県船橋市習志野台六丁目8 4棟304号',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L317',
    name: 'ban no pattern',
    input: '愛知県小牧市大字河内屋新田字下岩倉杁510番の1',
    expected: '愛知県小牧市大字河内屋新田字下岩倉杁510-1',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L323',
    name: 'ban gai pattern with full-width',
    input: '東京都港区台場一丁目５番街１号棟６０１号室',
    expected: '東京都港区台場一丁目5番街 1号棟601号室',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L329',
    name: 'ban building pattern',
    input: '神戸市中央区京町８０番クリエイト神戸９階',
    expected: '神戸市中央区京町80 クリエイト神戸9階',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L335',
    name: 'ban building pattern with same number',
    input: '神戸市中央区江戸町１０４番江戸町１０４ビル４階',
    expected: '神戸市中央区江戸町104 江戸町104ビル4階',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L341',
    name: 'ban no with additional no pattern',
    input: '東京都千代田区西神田二丁目６番７の２共和１５番館ビル２階',
    expected: '東京都千代田区西神田二丁目6-7-2 共和15番館ビル2階',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L347',
    name: 'banchi go tou pattern',
    input: '埼玉県三郷市早稲田六丁目１番地２号棟２０１号',
    expected: '埼玉県三郷市早稲田六丁目1 2号棟201号',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L353',
    name: 'address with parentheses',
    input: '東京都千代田区１番３号(東京ガーデンテラス)',
    expected: '東京都千代田区1-3 (東京ガーデンテラス)',
    addressType: 'rsdtdsp',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L359',
    name: 'address with parentheses and building',
    input: '東京都千代田区一番町５(アトラスビル５階)',
    expected: '東京都千代田区一番町5 (アトラスビル5階)',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L365',
    name: 'banchi pattern with machi',
    input: '新潟県新潟市東中通１番町１８８番地２',
    expected: '新潟県新潟市東中通1番町188-2',
    addressType: 'parcel',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L371',
    name: 'ichibancho with ban go building',
    input: '東京都千代田区一番町９番８号ノザワビル６Ｆ',
    expected: '東京都千代田区一番町9-8 ノザワビル6F',
    addressType: 'rsdtdsp',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L377',
    name: 'number followed by building name',
    input: '茨城県つくば市島名２３３５ウィンズヒル４Ｂ',
    expected: '茨城県つくば市島名2335 ウィンズヒル4B',
    addressType: 'unknown',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L383',
    name: 'room number with dash-hyphen',
    input: '東京都千代田区三崎町三丁目２番６−１１０４号室レジディア水道橋',
    expected: '東京都千代田区三崎町三丁目2-6 -1104号室レジディア水道橋',
    addressType: 'rsdtdsp',
  },
  {
    source: 'normalize_test.go TestNormalizeAddressText L389',
    name: 'ichibancho with hyphen and building',
    input: '東京都千代田区一番町4-4THECROSS一番町7階',
    expected: '東京都千代田区一番町4-4 THECROSS一番町7階',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeBasicNormalized L421',
    name: 'nil basicResult - same as NormalizeAddressText',
    input: '東京都千代田区紀尾井町1番3号',
    expected: '東京都千代田区紀尾井町1-3',
    addressType: 'rsdtdsp',
  },
  {
    source: 'normalize_test.go TestNormalizeBasicNormalized L428',
    name: 'with pre-computed basicResult',
    input: '東京都千代田区紀尾井町1番3号',
    expected: '東京都千代田区紀尾井町1-3',
    addressType: 'rsdtdsp',
  },
  {
    source: 'normalize_test.go TestNormalizeBasicNormalized L435',
    name: 'with NFKC conversion',
    input: '東京都千代田区紀尾井町１番３号',
    expected: '東京都千代田区紀尾井町1-3',
    addressType: 'rsdtdsp',
  },
  {
    source: 'normalize_test.go TestNormalizeBasicNormalized L442',
    name: 'with dash normalization',
    input: '東京都千代田区紀尾井町1—2—3',
    expected: '東京都千代田区紀尾井町1-2-3',
    addressType: 'undetermined',
  },
  {
    source: 'normalize_test.go TestNormalizeBasicNormalized L449',
    name: 'with building name',
    input: '兵庫県三田市三輪2-1-1三田市役所',
    expected: '兵庫県三田市三輪2-1-1 三田市役所',
    addressType: 'undetermined',
  },
];

export const DETECT_ADDRESS_TYPE_CASES: TypeCase[] = [
  {
    source: 'address_type_test.go TestDetectAddressType L16',
    name: 'ban pattern without go',
    input: '1番2',
    expected: 'undetermined',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L21',
    name: 'ban only pattern',
    input: '1310番',
    expected: 'undetermined',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L26',
    name: 'ban only pattern with address',
    input: '埼玉県川崎市幸区大宮町1310番',
    expected: 'undetermined',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L31',
    name: 'basic ban-go pattern',
    input: '1番2号',
    expected: 'rsdtdsp',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L36',
    name: 'ban-go with hyphenated address',
    input: '1番2-345号',
    expected: 'rsdtdsp',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L41',
    name: 'ban-go with multiple hyphens',
    input: '1番2-3-4号',
    expected: 'rsdtdsp',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L46',
    name: 'ban-go with many hyphens',
    input: '1番2-3-4-5-6号',
    expected: 'rsdtdsp',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L51',
    name: 'ban-go with alphanumeric suffix',
    input: '22番5-A1002号',
    expected: 'rsdtdsp',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L56',
    name: 'ban-go with full address',
    input: '東京都千代田区紀尾井町1番3号',
    expected: 'rsdtdsp',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L61',
    name: 'ban-go with half-width space',
    input: '千代田区 1番2号',
    expected: 'unknown',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L66',
    name: 'three digit ban-go',
    input: '123番456号',
    expected: 'rsdtdsp',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L73',
    name: 'basic banchi pattern',
    input: '1番地',
    expected: 'parcel',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L78',
    name: 'banchi with number',
    input: '1番地2',
    expected: 'parcel',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L83',
    name: 'banchi no pattern',
    input: '1番地の2',
    expected: 'parcel',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L88',
    name: 'banchi with full address',
    input: '東京都世田谷区1番地',
    expected: 'parcel',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L93',
    name: 'banchi no with full address',
    input: '東京都世田谷区1番地の2',
    expected: 'parcel',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L98',
    name: 'banchi number with full address',
    input: '東京都世田谷区1番地3',
    expected: 'parcel',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L103',
    name: 'large banchi numbers',
    input: '123番地456',
    expected: 'parcel',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L108',
    name: 'Okayama Niimi banchi with space',
    input: '岡山県新見市神郷下神代 2029番地',
    expected: 'unknown',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L115',
    name: 'arabic dash pattern',
    input: '1-2-3',
    expected: 'undetermined',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L120',
    name: 'arabic dash with prefecture',
    input: '東京都千代田区1-2-3',
    expected: 'undetermined',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L125',
    name: 'incorrect format banchi-go',
    input: '1番地2号',
    expected: 'undetermined',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L130',
    name: 'incorrect format banchi-go with address',
    input: '東京都千代田区1番地2号',
    expected: 'undetermined',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L135',
    name: 'incorrect format banchi with hyphenated go',
    input: '8番地20-101号',
    expected: 'undetermined',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L140',
    name: 'incorrect format banchi with hyphenated go and address',
    input: '東京都千代田区神田多町二丁目8番地20-101号',
    expected: 'undetermined',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L147',
    name: 'prefecture only',
    input: '東京都',
    expected: 'unknown',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L152',
    name: 'city only',
    input: '千代田区',
    expected: 'unknown',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L157',
    name: 'empty string',
    input: '',
    expected: 'unknown',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L162',
    name: 'only chome',
    input: '1丁目',
    expected: 'unknown',
  },
  {
    source: 'address_type_test.go TestDetectAddressType L167',
    name: 'mixed patterns without clear indicators',
    input: '東京都千代田区丸の内',
    expected: 'unknown',
  },
];

export const BASIC_NORMALIZE_CASES: StringCase[] = [
  {
    source: 'pipeline_test.go TestBasicNormalize L11',
    name: 'empty string',
    input: '',
    expected: '',
  },
  {
    source: 'pipeline_test.go TestBasicNormalize L16',
    name: 'no change needed',
    input: '東京都千代田区',
    expected: '東京都千代田区',
  },
  {
    source: 'pipeline_test.go TestBasicNormalize L21',
    name: 'removes surrounding quotes',
    input: '"東京都千代田区"',
    expected: '東京都千代田区',
  },
  {
    source: 'pipeline_test.go TestBasicNormalize L26',
    name: 'removes variation selectors',
    input: '愛媛\u{e0103}県',
    expected: '愛媛県',
  },
  {
    source: 'pipeline_test.go TestBasicNormalize L31',
    name: 'standardizes spaces',
    input: '東京都\u3000千代田区',
    expected: '東京都 千代田区',
  },
  {
    source: 'pipeline_test.go TestBasicNormalize L36',
    name: 'removes newlines',
    input: '東京都\n千代田区',
    expected: '東京都 千代田区',
  },
  {
    source: 'pipeline_test.go TestBasicNormalize L41',
    name: 'removes comments',
    input: '東京都千代田区// コメント',
    expected: '東京都千代田区',
  },
  {
    source: 'pipeline_test.go TestBasicNormalize L46',
    name: 'NFKC normalization - full-width to half-width',
    input: '１２３',
    expected: '123',
  },
  {
    source: 'pipeline_test.go TestBasicNormalize L51',
    name: 'normalizes dashes',
    input: '東京都千代田区1—2',
    expected: '東京都千代田区1-2',
  },
  {
    source: 'pipeline_test.go TestBasicNormalize L56',
    name: 'normalizes halfwidth katakana prolonged sound mark',
    input: '1ｰ2ｰ3',
    expected: '1-2-3',
  },
  {
    source: 'pipeline_test.go TestBasicNormalize L62',
    name: 'halfwidth katakana dash with full-width digits',
    input: '東京都千代田区１ｰ２ｰ３',
    expected: '東京都千代田区1-2-3',
  },
  {
    source: 'pipeline_test.go TestBasicNormalize L67',
    name: 'combined transformations - quotes',
    input: '"東京都\u3000１−２"',
    expected: '東京都 1-2',
  },
  {
    source: 'pipeline_test.go TestBasicNormalize L72',
    name: 'combined transformations - comment',
    input: '東京都\u3000１−２// test',
    expected: '東京都 1-2',
  },
  {
    source: 'pipeline_test.go TestBasicNormalize_Pipeline L94',
    name: 'pipeline order',
    input: '"\u3000東京都１−２\u3000"',
    expected: '東京都1-2',
  },
];
